/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.programa2futoshiki;

import javax.swing.JOptionPane;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.*;
import java.awt.*;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
/**
 *
 * @author XPC
 */
public class MenuConfigurar extends javax.swing.JFrame{

    /**
     * Creates new form MenuConfigurar
     */
    private ArrayList<AjustesFutoshiki> Ajustes = new ArrayList<>();
    
    MenuPrincipal menu = new MenuPrincipal();
    
    Usuario usuario;
    
    private String nombre;
    private int Tablero;
    private String Dificultad;
    private int MultiNivel;
    private int UsoReloj;
    private String Posicion;
    
    /*
    private String nombre;
    private int Tablero = getTam(); 
    private String Dificultad = getDificultad();
    private int MultiNivel = getMultiNivel(); // 0 : No  1: Si
    private int UsoReloj = getReloj(); // 0 : Cronometro  1: Temporizador   2: No
    private String Posicion = getPosicion();
    */
    
    public MenuConfigurar(){
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboxTamaño2 = new javax.swing.JComboBox<>();
        txtTitulo = new javax.swing.JLabel();
        lblTamaño = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblMultiNivel = new javax.swing.JLabel();
        botonJugar = new javax.swing.JButton();
        lblReloj = new javax.swing.JLabel();
        lblReloj1 = new javax.swing.JLabel();
        cboxTamaño = new javax.swing.JComboBox<>();

        cboxTamaño.setRenderer(new javax.swing.ListCellRenderer<String>() {
            
            @Override
            public Component getListCellRendererComponent(JList<? extends String> list, String value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel label = new JLabel(value);
                label.setFont(new java.awt.Font("Dialog", 0, 14));

                if (index == 0) {
                    label.setForeground(Color.RED);
                } else {
                    label.setForeground(Color.BLACK);
                }

                if (isSelected) {
                    label.setBackground(Color.LIGHT_GRAY);
                    label.setOpaque(true);
                }
                
                return label;
            }
        });

        cboxNivel = new javax.swing.JComboBox<>();

        cboxNivel.setRenderer(new javax.swing.ListCellRenderer<String>() {

            @Override
            public Component getListCellRendererComponent(JList<? extends String> list, String value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel label = new JLabel(value);
                label.setFont(new java.awt.Font("Dialog", 0, 14));

                if (index == 0) {
                    label.setForeground(Color.RED);
                } else {
                    label.setForeground(Color.BLACK);
                }

                if (isSelected) {
                    label.setBackground(Color.LIGHT_GRAY);
                    label.setOpaque(true);
                }
                
                return label;
            }
        });

        cboxMultiNivel = new javax.swing.JComboBox<>();

        cboxMultiNivel.setRenderer(new javax.swing.ListCellRenderer<String>() {

            @Override
            public Component getListCellRendererComponent(JList<? extends String> list, String value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel label = new JLabel(value);
                label.setFont(new java.awt.Font("Dialog", 0, 14));

                if (index == 0) {
                    label.setForeground(Color.RED);
                } else {
                    label.setForeground(Color.BLACK);
                }

                if (isSelected) {
                    label.setBackground(Color.LIGHT_GRAY);
                    label.setOpaque(true);
                }
                
                return label;
            }
        });

        cboxReloj = new javax.swing.JComboBox<>();

        cboxReloj.setRenderer(new javax.swing.ListCellRenderer<String>() {

            @Override
            public Component getListCellRendererComponent(JList<? extends String> list, String value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel label = new JLabel(value);
                label.setFont(new java.awt.Font("Dialog", 0, 14));

                if (index == 0) {
                    label.setForeground(Color.RED);
                } else {
                    label.setForeground(Color.BLACK);
                }

                if (isSelected) {
                    label.setBackground(Color.LIGHT_GRAY);
                    label.setOpaque(true);
                }
                
                return label;
            }
        });

        cboxPosicion = new javax.swing.JComboBox<>();

        cboxPosicion.setRenderer(new javax.swing.ListCellRenderer<String>() {

            @Override
            public Component getListCellRendererComponent(JList<? extends String> list, String value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel label = new JLabel(value);
                label.setFont(new java.awt.Font("Dialog", 0, 14));

                if (index == 0) {
                    label.setForeground(Color.RED);
                } else {
                    label.setForeground(Color.BLACK);
                }

                if (isSelected) {
                    label.setBackground(Color.LIGHT_GRAY);
                    label.setOpaque(true);
                }
                
                return label;
            }
        });

        botonSalir = new javax.swing.JButton();
        lblJugador = new javax.swing.JLabel();
        txtfUsuario = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        cboxTamaño2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cboxTamaño2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxTamaño2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTamaño2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTitulo.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Configuración de la Partida");

        lblTamaño.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTamaño.setText("Tamaño de la cuadrícula:");

        lblNivel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblNivel.setText("Nivel del juego:");

        lblMultiNivel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblMultiNivel.setText("Multinivel:");

        botonJugar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        botonJugar.setText("Jugar");
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });

        lblReloj.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblReloj.setText("Uso del reloj:");

        lblReloj1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblReloj1.setText("Posición de los dígitos:");

        cboxTamaño.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cboxTamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4x4", "5x5", "6x6", "7x7", "8x8", "9x9", "10x10" }));
        cboxTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTamañoActionPerformed(evt);
            }
        });

        cboxNivel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cboxNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Intermedio", "Difícil" }));
        cboxNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxNivelActionPerformed(evt);
            }
        });

        cboxMultiNivel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cboxMultiNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No ", "Si" }));
        cboxMultiNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxMultiNivelActionPerformed(evt);
            }
        });

        cboxReloj.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cboxReloj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cronómetro ", "Temporizador", "No" }));
        cboxReloj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxRelojActionPerformed(evt);
            }
        });

        cboxPosicion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cboxPosicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Derecha", "Izquierda" }));
        cboxPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxPosicionActionPerformed(evt);
            }
        });

        botonSalir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        lblJugador.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblJugador.setText("Nombre de Jugador:");

        txtfUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        Guardar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(botonSalir)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTamaño)
                            .addComponent(lblNivel)
                            .addComponent(lblMultiNivel)
                            .addComponent(lblReloj)
                            .addComponent(lblReloj1)
                            .addComponent(lblJugador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboxPosicion, 0, 234, Short.MAX_VALUE)
                            .addComponent(cboxReloj, 0, 234, Short.MAX_VALUE)
                            .addComponent(cboxMultiNivel, 0, 234, Short.MAX_VALUE)
                            .addComponent(cboxNivel, 0, 234, Short.MAX_VALUE)
                            .addComponent(cboxTamaño, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtfUsuario)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(56, 56, 56)
                        .addComponent(botonJugar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(botonSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(jButton1))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTamaño)
                    .addComponent(cboxTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNivel)
                    .addComponent(cboxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMultiNivel)
                    .addComponent(cboxMultiNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReloj)
                    .addComponent(cboxReloj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReloj1)
                    .addComponent(cboxPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJugador)
                    .addComponent(txtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(botonJugar)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTamañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxTamañoActionPerformed

    private void cboxNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxNivelActionPerformed

    private void cboxTamaño2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTamaño2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxTamaño2ActionPerformed

    private void cboxMultiNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxMultiNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxMultiNivelActionPerformed

    private void cboxRelojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxRelojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxRelojActionPerformed

    private void cboxPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxPosicionActionPerformed

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
        // TODO add your handling code here:

        
        //ValidarUsuario();
        setAjustes();
        
        
        switch(Tablero){
            
            case 0 : // 4x4
                break;
            
            case 1: // 5x5
                break;
            
            case 2: // 6x6
                break;
                
            case 3: // 7x7
                break;
                
            case 4: // 8x8
                break;
            
            case 5: // 9x9
                break;
            
            case 6: // 10x10
                new Frame10x10(Dificultad,MultiNivel,UsoReloj,Posicion,nombre,usuario).setVisible(true);
                setVisible(false);
                break;
        }
          
    }//GEN-LAST:event_botonJugarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:

        setVisible(false);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        setAjustes();
        
    }//GEN-LAST:event_GuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RestaurarAjustes();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public String getDificultad(){
          
        return cboxNivel.getSelectedItem().toString();
    }
    
    public int getMultiNivel(){
        
        return cboxMultiNivel.getSelectedIndex();
    }
    
    public int getReloj(){
            
        return cboxReloj.getSelectedIndex();      
    }
    
    public String getPosicion(){
     
        return cboxPosicion.getSelectedItem().toString();    

    }
    public int getTam(){
    
        return cboxTamaño.getSelectedIndex();
    
    }
    
    public void ValidarUsuario(){
      
      try{
        if(txtfUsuario.getText().equalsIgnoreCase("") ||txtfUsuario.getText().equalsIgnoreCase("Anónimo")){
            
            nombre = "Anónimo";
            
        }else{
            String pin = JOptionPane.showInputDialog(null, "Ingrese el PIN del usuario:");
            usuario = menu.ValidarUsuarioPIN(txtfUsuario.getText(), pin);
            
            if(usuario!=null){
                
                JOptionPane.showMessageDialog(null, "Se jugara como usuario : "+ usuario.Nickname);
                nombre = usuario.Nickname;
            }else{
            
                JOptionPane.showMessageDialog(null, "No se encuentra al usuario, se procedera como usuario anónimo");
                nombre = "Anónimo";
            }
        }
      }catch(Exception e){
          
          e.printStackTrace();
      }
    }
    
    
    public void setAjustes(){
        cargarAjustes();
        
       ValidarUsuario(); 
       Tablero = getTam(); 
       Dificultad = getDificultad();
       MultiNivel = getMultiNivel(); // 0 : No  1: Si
       UsoReloj = getReloj(); // 0 : Cronometro  1: Temporizador   2: No
       Posicion = getPosicion();
       
       Ajustes.add(new AjustesFutoshiki(nombre, Tablero,cboxNivel.getSelectedIndex(),MultiNivel,
                      UsoReloj,cboxPosicion.getSelectedIndex()));
       
       guardarAjustes();
    
    }
    
    public void RestaurarAjustes(){
    
        cargarAjustes();
        AjustesFutoshiki ajuste = Ajuste();
        
        if(ajuste!=null){
        
            cboxTamaño.setSelectedIndex(ajuste.IndiceTam);
            cboxNivel.setSelectedIndex(ajuste.IndiceNivel);
            cboxMultiNivel.setSelectedIndex(ajuste.IndiceMultiNivel);
            cboxReloj.setSelectedIndex(ajuste.IndiceReloj);
            cboxPosicion.setSelectedIndex(ajuste.IndiceReloj);
            txtfUsuario.setText(ajuste.nombre);
        }else{
        
            JOptionPane.showMessageDialog(null, "No hay ajustes previos.");
        }
    
    }
    
    public void guardarAjustes(){
        
        //cargarAjustes();
        
        if(Ajustes.size()==2){
        
            Ajustes.remove(0);
        }
        
        try(ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("futoshiki2024configuración.dat"))){
            
            oos.writeObject(Ajustes);

        }catch (IOException e){
            System.out.println("Error al guardar los datos.");
        }
    }

    public void cargarAjustes(){
    
        try(ObjectInputStream ois = new ObjectInputStream(new FileInputStream("futoshiki2024configuración.dat"))) {
            
            Ajustes = (ArrayList<AjustesFutoshiki>) ois.readObject();

        }catch (IOException | ClassNotFoundException e){
            
            System.out.println("Error al cargar los datos.");
        }
    } 
    
    public AjustesFutoshiki Ajuste(){
        
        cargarAjustes();
        for( AjustesFutoshiki ajuste: Ajustes ){
        
            return ajuste;
            
        
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> cboxMultiNivel;
    private javax.swing.JComboBox<String> cboxNivel;
    private javax.swing.JComboBox<String> cboxPosicion;
    private javax.swing.JComboBox<String> cboxReloj;
    private javax.swing.JComboBox<String> cboxTamaño;
    private javax.swing.JComboBox<String> cboxTamaño2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblMultiNivel;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JLabel lblReloj1;
    private javax.swing.JLabel lblTamaño;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JTextField txtfUsuario;
    // End of variables declaration//GEN-END:variables
}
