/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programa;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author XPC
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    
    
    SistemaCorreos correos = new SistemaCorreos();
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jProgressBar1 = new javax.swing.JProgressBar();
        jTextField1 = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JLabel();
        botonJugar = new javax.swing.JButton();
        BotonRegistro = new javax.swing.JButton();
        botonTop = new javax.swing.JButton();
        botonAcercaDe = new javax.swing.JButton();
        botonManual = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonPIN = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTitulo.setFont(new java.awt.Font("Dialog", 1, 56)); // NOI18N
        txtTitulo.setText("Futoshiki");

        botonJugar.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        botonJugar.setText("Jugar");
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });

        BotonRegistro.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        BotonRegistro.setText("Registrarse");
        BotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroActionPerformed(evt);
            }
        });

        botonTop.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        botonTop.setText("Top 10");
        botonTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTopActionPerformed(evt);
            }
        });

        botonAcercaDe.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        botonAcercaDe.setText("Acerca de ");

        botonManual.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        botonManual.setText("Manual de Uso");
        botonManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonManualActionPerformed(evt);
            }
        });

        botonSalir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonPIN.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        botonPIN.setText("Olvide mi PIN");
        botonPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPINActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(botonJugar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(BotonRegistro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(botonTop)))
                .addGap(173, 173, 173))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonPIN)
                    .addComponent(botonSalir)
                    .addComponent(botonAcercaDe)
                    .addComponent(botonManual))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(botonSalir)
                .addGap(44, 44, 44)
                .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(99, 99, 99)
                .addComponent(botonJugar)
                .addGap(39, 39, 39)
                .addComponent(BotonRegistro)
                .addGap(30, 30, 30)
                .addComponent(botonTop)
                .addGap(66, 66, 66)
                .addComponent(botonPIN)
                .addGap(18, 18, 18)
                .addComponent(botonAcercaDe)
                .addGap(18, 18, 18)
                .addComponent(botonManual)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
        // TODO add your handling code here:
        
        String[] opciones = {"4x4", "5x5","6x6 ","7x7","8x8","9x9",
            "10x10", "Salir"}; 
        
        int tablero = JOptionPane.showOptionDialog(
                null,
                "Seleccione el tamaño del tablero con el que se quiere jugar:",
                "Menú de Opciones de Tablero",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                opciones,
                opciones[0]
        );
        
        switch(tablero){
        
            case 0:
                //4x4
                break;
                
            case 1:
                //5x5
                break;
                
            case 2:
                //6x6
                break;
                
            case 3:
                //7x7
                break;
            case 4:
                //8x8 
                break;
            case 5:
                //9x9
                break;
            case 6:
                //10x10
                new Frame10x10().setVisible(true);
                //setVisible(false);
                break;
                
            case 7:
                //Salir
                break;
        }
        
    }//GEN-LAST:event_botonJugarActionPerformed

    private void botonManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonManualActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void BotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroActionPerformed
        // TODO add your handling code here:
        
        MenuRegistro registro = new MenuRegistro();
        
        registro.setVisible(true);
        
    }//GEN-LAST:event_BotonRegistroActionPerformed

    private void botonTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTopActionPerformed
        
        // Prueba
        cargarDatos();
        mostrarUsuario();
    }//GEN-LAST:event_botonTopActionPerformed

    private void botonPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPINActionPerformed
        
        //cargarDatos();
        String nick = JOptionPane.showInputDialog("Ingrese el nombre de usuario");
        
        NuevoPIN(nick);
        
        
    }//GEN-LAST:event_botonPINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            
            public void run() {
                new MenuPrincipal().setVisible(true);
                
                
                
            }
            
        });
    }
    
    private ArrayList<Usuario> usuarios = new ArrayList<>();
    
    public void agregarUsuario(Usuario usuario) {
        
        usuarios.add(usuario);
    }
    
    public void guardarDatos(){
        
        try(ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("usuarios.dat"))){
            
            oos.writeObject(usuarios);

        }catch (IOException e){
            System.out.println("Error al guardar los datos.");
        }
    }
    
    public void cargarDatos(){
    
        try(ObjectInputStream ois = new ObjectInputStream(new FileInputStream("usuarios.dat"))) {
            
            usuarios = (ArrayList<Usuario>) ois.readObject();

        }catch (IOException | ClassNotFoundException e){
            
            System.out.println("Error al cargar los datos.");
        }
    }
    
    public void mostrarUsuario(){
      
       if(usuarios.size()!=0){
       
         for(Usuario usuario: usuarios){
        
            System.out.println("\nUsuario: "+ usuario.Nickname);
        
          }
       
       }else{
           System.out.println("No hay un registro");
       }
        
    }
    
    public void NuevoPIN(String nick){
        
        
        cargarDatos();
        Usuario usuario = ValidarSoloUsuario(nick);
        
        if( usuario != null){
        
            String cadenaAleatoria = generarStringAleatorio(4); // Pin aletorio
            System.out.println("El nuevo PIN del usuario "+ usuario.Nickname + " es: "
            + cadenaAleatoria); // debugging
            
            usuario.Pin = cadenaAleatoria; // Guardado de pin
            guardarDatos();
            
            JOptionPane.showMessageDialog(null,"Se ha enviado un correo con el PIN de recuperacion.");
            correos.EnviarCorreoNuevoPin(usuario);

        }else{
        
            JOptionPane.showMessageDialog(null,"Usuario no encontrado.");
        
        }
    }  
    
    public Usuario ValidarSoloUsuario(String nombre) {
        
        
        for (Usuario usuario : usuarios) {
            
            if (usuario.Nickname.equalsIgnoreCase(nombre)) {
                
                    return usuario; // Devuelve el usuario encontrado
                
            }
        }
        return null; // Si no se encuentra ningún usuario con ese nombre
    } 
    
    
    public String generarStringAleatorio(int longitud) { 
                                                                   
        String letras = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
        Random random = new Random();
        StringBuilder sb = new StringBuilder(longitud);

        for (int i = 0; i < longitud; i++){
            
            int indice = random.nextInt(letras.length());
            sb.append(letras.charAt(indice));
            
        }
        
        return sb.toString();
    }    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegistro;
    private javax.swing.JButton botonAcercaDe;
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton botonManual;
    private javax.swing.JButton botonPIN;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonTop;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables

}
